### ISSUE TITLE
Need to correct typo mistake in 2magento add column

### ISSUE THREAD

**Issue by rltsquare** [staempfli/magento2-code-generator#10]
Can you please fix the type of `length` when we use 2magento add column ? This is what I am getting:

```
$setup->getConnection()->addColumn(
            $setup->getTable(''),
            '',
            [
                'type' => Table::TYPE_,
                'lenght' => null,
                'nullable' => true,
                'default' => '',
                'comment' => '',
            ]
        );
```

**Comment by jalogut** [comment]
Hi @rltsquare 

I think this issue belongs to a different project:

- https://github.com/staempfli/magento2-phpstorm-templates

I'll fix it there. Thanks

**Comment by jalogut** [comment]
@rltsquare it is fixed in the other project:

- https://github.com/staempfli/magento2-phpstorm-templates/releases/tag/1.6.2
