### ISSUE TITLE
mg2-codepen command not found

### ISSUE THREAD

**Issue by birdman002** [staempfli/magento2-code-generator#18]
I have installed codepen via composer made sure my path was correct. Now no matter what folder I run this any mg2 commands from i get the mg2-codepen command not found.

Kinda unsure what to do! Any help would be greatly appreciated

**Comment by jalogut** [comment]
Hi @birdman002 

It is `mg2-codegen` not `mg2-codepen`. Could you let me know your outputs for these commands:

* `composer config --list --global | grep home`
* `echo $PATH`
* `which mg2-codegen`

**Comment by jalogut** [comment]
Hi @birdman002 

Just as info for others, the problem here was that the composer bin was not configured properly in the`$PATH`. Happy that you manage to solve it :)
