### ISSUE TITLE
Undefined Index Notice While Generating Module

### ISSUE THREAD

**Issue by Partabsaifzakir** [staempfli/magento2-code-generator#23]
Why i'm getting this ???

# mg2-codegen t:g module
PHP Notice:  Undefined index: HOME in C:\Users\S.P Zakir\AppData\Roaming\Composer\vendor\staempfli\universal-code-generator\src\Staempfli\UniversalGenerator\Helper\Files\ApplicationFilesHelper.php on line 58

Notice: Undefined index: HOME in C:\Users\S.P Zakir\AppData\Roaming\Composer\vendor\staempfli\universal-code-generator\src\Staempfli\UniversalGenerator\Helper\Files\ApplicationFilesHelper.php on line 58
Template Generate: module
PHP Notice:  Undefined index: HOME in C:\Users\S.P Zakir\AppData\Roaming\Composer\vendor\staempfli\universal-code-generator\src\Staempfli\UniversalGenerator\Helper\Files\ApplicationFilesHelper.php on line 58

Notice: Undefined index: HOME in C:\Users\S.P Zakir\AppData\Roaming\Composer\vendor\staempfli\universal-code-generator\src\Staempfli\UniversalGenerator\Helper\Files\ApplicationFilesHelper.php on line 58

**Comment by piotrkwiecinski** [comment]
From the path it looks like you're on windows.

Current implementation only handles HOME variable in server: https://github.com/staempfli/universal-code-generator/blob/master/src/Staempfli/UniversalGenerator/Helper/Files/ApplicationFilesHelper.php#L56-L59

Composer has it implemented like: https://github.com/composer/composer/blob/master/src/Composer/Util/Platform.php#L48-L64

There may be more issues with support for windows.

If no one grabs it I'll try to PR it at the end of the week.

**Comment by jalogut** [comment]
Hi @Partabsaifzakir and @piotrkwiecinski 
 
I merged the PR from @piotrkwiecinski and created a new version 1.11.2. Thanks for the contribution and sorry for the delay.
