### ISSUE TITLE
Phar file?

### ISSUE THREAD

**Issue by seansan** [staempfli/magento2-code-generator#24]
Can we download phar file directly from repo using link to master? (cant find the <version> version)

Also is this compatible and according to M2.3.1.standards?

Thanks.

**Comment by gfernandes410** [comment]
I'm using it with 2.3.1 and didn't have any problem.

**Comment by jlnarvaez** [comment]
@seansan You can get latest version with this command:
   

`wget https://github.com/staempfli/magento2-code-generator/releases/latest/download/mg2-codegen.phar `
