### ISSUE TITLE
Irrelevant datasource name in some templates?

### ISSUE THREAD

**Issue by rev42** [staempfli/magento2-code-generator#6]
I found some irrelevant datasource names. 

Is it intended to prepend them with "computer_games"?

`<dataSource name="computer_games_form_data_source">`

Found in:
- templates/crud/view/adminhtml/ui_component/${vendorname}_${modulename}_${entityname}_form.xml
- templates/crudEAV/view/adminhtml/ui_component/${vendorname}_${modulename}_${entityname}_form.xml

**Comment by jalogut** [comment]
Hi @rev42 , 

Thanks for noticing. I just fixed that together with your PR on version 1.6.4

Thanks for your contribution.
