### ISSUE TITLE
Please clarify the license of the generated code

### ISSUE THREAD

**Issue by fooman** [staempfli/magento2-code-generator#7]
Thanks for providing this code generator - after reading [this](https://softwareengineering.stackexchange.com/a/221607) and seeing that it might be arguable how much of the code (ie the templates) end up in the final generated output can you please clarify what the output is licensed under?

**Comment by jalogut** [comment]
Hi @fooman,

Thanks for pointing that out. I just updated the license section.

* Commit: https://github.com/staempfli/magento2-code-generator/commit/a19b4b777ad7fbd2249a488a1ddaa311b2c55fa2
